### PR TITLE
1st try

### PR DESCRIPTION
**Pull request by vektor8**
no comment

### CODE REVIEW

**Review by Ranapop — CHANGES_REQUESTED** [review]
Two notes:
->from a functionality perspective: for additional info, if the user simply hits enter, you shouldn't display the "additional info" entry in your order
->from a code perspective: try to stick to one naming convention (you have some variables with camel case, while for other variables all letters are lower case, no separator between words)

**Comment by vektor8** [comment]
2nd try:
-doesn't display the "additional info" entry in the order if there is no additional info introduced by the user
-changed all variables to be named according to the camel case rule

**Review by Ranapop — APPROVED** [review]
e ok. 10

**Comment by vektor8** [comment]
Danke schön

**Pull request merged**
